---
title: "Gráficos de correlação entre variáveis no R"
author: "Melina de Souza Leite http://melinaleite.weebly.com/"
date: "`r format(Sys.time(), '%d de %B de %Y')`"
bibliography: refs.bib
output:
  rmdformats::readthedown:
    highlight: kate
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: false
---

```{r setup, echo=FALSE, warning=FALSE, message=F}
#install_github("melina-leite/rmdformats")
library(knitr)
library(skimr)
library(ggplot2)
library(tidyverse)

opts_chunk$set(
  fig.align = "center", fig.show = "hold", fig.height = 4,
  warning = F, message = F, error = F, cache = T
)
options(formatR.arrow = TRUE, width = 90)
```

É muito comum que tenhamos um conjunto de dados com muitas variáveis (colunas) e queiramos saber a relação entres estas variáveis, por exemplo quais são mais ou menos correlacionadas entre si (positiva ou negativamente).

Avaliar as correlações entre variáveis é um dos primeiros passos em uma análise de dados e serve tanto como exploração e tomada de decisão em análises multivariadas como em análises baseadas em modelos (nas quais se tem muitas variáveis preditoras que não devem estar relacionadas - o problema da colinearidade entre variáveis confundindo a estimação dos coeficientes).

Neste roteiro, pretendo explorar algumas ferramentas e funções gráficas sobre correlações que fui encontrando em diversos materiais. 

Para fazer esse roteiro, é esperado que o leitor já saiba o que é uma [correlação](https://pt.wikipedia.org/wiki/Correla%C3%A7%C3%A3o) entre duas variáveis e tenha conhecimento básico de R.

Vamos também utilizar o conjunto de dados de exemplo

USAR EXEMPLO DO DATASAURUS!!! ANSCOMBE QUARTETO E MUITO MAIS

# Matriz de plots

O plot de Draftman, também conhecido como matriz de plots (tradução minha para _scatter plot matrix_), pode ser computado no R com a simples função `pairs`, mas diversos usuários já criaram versões personalizadas destes plots. 



1. correlações:
- tipos de correlação
- como calcular, funções e pacotes
- diferentes formas de apresentar figuras, funções e pacotes
- Material:
- ggally, ggcorr, ggpairs, função que o stefan apresentou com heatmap
- tutorial p criar redes de correlação corrr gggraph (https://drsimonj.svbtle.com/how-to-create-correlation-network-plots-with-corrr-and-ggraph)
- corrgram package - correlogramas
- ver script capt 3 do Manly 2017 - vários plots de correlação.
- ver livros do zuur com as funções próprias pra fazer o pairs, também o Borcard et al. 2011 tem funções para usar no Pairs.
- 


<!---
# Correlação entre duas variáveis, o que é isso?

Antes de partir diretamente para os gráficos bonitinhos, vamos entender brevemente o que é uma correlação, quais os tipos de correlação mais utilizados e recomendados para diferentes tipos de dados e como se testa significância do valor de correlação.

A correlação é uma medida de associação/relação entre duas variáveis (X e Y). Ela é definida em termos da variância de X, da variância de Y, e da covariância (a maneira na qual as duas variam juntas) entre X e Y. Podemos dizer que a correlação é uma medida padronizada da covariância. Logo o coeficiente de correlação $r$ é:

$$r = \frac{cov(x,y)}{\sqrt{var(x)*var(y)}}$$

A função mais básica de correlação no R é a `cor`, 

--->






